# Generated by Django 5.1.2 on 2024-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDetals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default="bag", max_length=50)),
                (
                    "product_description",
                    models.TextField(default="Importance of description"),
                ),
            ],
        ),
    ]
